#!/usr/bin/env python3
"""
Bridges Spec Agent patch requests to Serena (or a fallback stub).

The wrapper reads a JSON payload from stdin with the following shape:
{
    "repo_path": "/path/to/repo",
    "plan_id": "...",
    "step_description": "..."
}

It must emit a JSON payload with `diff`, `rationale`, and `alternatives`
for the patch engine to consume. When the SERENA_PATCH_DELEGATE environment
variable is set, this script forwards the payload to that command; otherwise
it returns a deterministic placeholder diff so the integration can be tested
without a running Serena instance.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path
from textwrap import dedent


def _run_delegate(command: str, payload: dict) -> str:
    completed = subprocess.run(
        shlex.split(command),
        input=json.dumps(payload),
        text=True,
        capture_output=True,
        check=True,
    )
    return completed.stdout


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "step"


def _placeholder_response(repo_path: Path, plan_id: str, step_description: str) -> dict:
    slug = _slugify(step_description)[:40]
    note_path = Path(".spec_agent") / "serena" / f"{plan_id}-{slug}.md"
    diff = dedent(
        f"""\
        --- a/{note_path}
        +++ b/{note_path}
        @@
        +## {step_description.strip()}
        +
        +- Repository: {repo_path}
        +- Plan ID: {plan_id}
        +- Generated by serena_patch_wrapper placeholder.
        """
    )
    rationale = "Placeholder diff produced by serena_patch_wrapper; replace via SERENA_PATCH_DELEGATE for real Serena output."
    alternatives = [
        "Call Serena MCP server with an LLM prompt describing the plan step.",
        "Fallback to manual edit and rerun the wrapper.",
    ]
    return {"diff": diff, "rationale": rationale, "alternatives": alternatives}


def main() -> int:
    payload = json.loads(sys.stdin.read() or "{}")
    repo_path = Path(payload.get("repo_path", "."))
    plan_id = payload.get("plan_id", "unknown-plan")
    step_description = payload.get("step_description", "unspecified step")

    delegate_cmd = os.getenv("SERENA_PATCH_DELEGATE")
    if delegate_cmd:
        stdout = _run_delegate(delegate_cmd, payload)
        sys.stdout.write(stdout)
        return 0

    response = _placeholder_response(repo_path, plan_id, step_description)
    json.dump(response, sys.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

