#!/usr/bin/env python3
"""
Bridges Spec Agent patch requests to Serena (or a fallback stub).

The wrapper reads a JSON payload from stdin with the following shape:
{
    "repo_path": "/path/to/repo",
    "plan_id": "...",
    "step_description": "..."
}

It must emit a JSON payload with `diff`, `rationale`, and `alternatives`
for the patch engine to consume. When the SERENA_PATCH_DELEGATE environment
variable is set, this script forwards the payload to that command; otherwise
it returns a deterministic placeholder diff so the integration can be tested
without a running Serena instance.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path
from textwrap import dedent


def _run_delegate(command: str, payload: dict) -> str:
    completed = subprocess.run(
        shlex.split(command),
        input=json.dumps(payload),
        text=True,
        capture_output=True,
        check=True,
    )
    return completed.stdout


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "step"


def _placeholder_response(repo_path: Path, plan_id: str, step_description: str) -> dict:
    slug = _slugify(step_description)[:40]
    note_path = Path(".spec_agent") / "serena" / f"{plan_id}-{slug}.md"
    diff = dedent(
        f"""\
        --- a/{note_path}
        +++ b/{note_path}
        @@
        +## {step_description.strip()}
        +
        +- Repository: {repo_path}
        +- Plan ID: {plan_id}
        +- Generated by serena_patch_wrapper placeholder.
        """
    )
    rationale = (
        "Placeholder diff produced by serena_patch_wrapper. "
        "To use real Serena integration:\n"
        "1. Install MCP: pip install mcp\n"
        "2. Set SERENA_PATCH_DELEGATE: export SERENA_PATCH_DELEGATE='python $(pwd)/scripts/serena_mcp_integration.py'\n"
        "3. Or configure in ~/.spec_agent/env"
    )
    alternatives = [
        "Set SERENA_PATCH_DELEGATE environment variable to point to serena_mcp_integration.py",
        "Install MCP library: pip install mcp",
        "Configure Serena MCP server command via SERENA_MCP_COMMAND",
    ]
    return {"diff": diff, "rationale": rationale, "alternatives": alternatives}


def main() -> int:
    payload = json.loads(sys.stdin.read() or "{}")
    repo_path = Path(payload.get("repo_path", "."))
    plan_id = payload.get("plan_id", "unknown-plan")
    step_description = payload.get("step_description", "Apply changes")
    
    delegate = os.environ.get("SERENA_PATCH_DELEGATE")
    
    if delegate:
        result_json = _run_delegate(delegate, payload)
        print(result_json, end="")
    else:
        result = _placeholder_response(repo_path, plan_id, step_description)
        print(json.dumps(result, indent=2))
    
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

